version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-maps-app
    restart : "no"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: maps_app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
volumes:
  mysql-data:
